Feature/226 init rails application
infinum/rails-jsonapi-example-app pull request #2
Opened 2020-09-10 08:33 UTC by martincekada

2020-09-10 09:11 UTC, d4be4st requested changes

2020-09-10 09:11 UTC, d4be4st commented on .github/CODEOWNERS
> +* @d4be4st @melcha @nikone @cilim @nikajukic @uncoverd @PetarCurkovic @JureCindro @vr4b4c @mateaaa @jerko-culina @anamarijabalaban @lovro-bikic @cukoreva
you are missing here :D
Also jan is missing

2020-09-10 09:11 UTC, d4be4st commented on .rubocop.yml
> +  - rubocop-rspec
use rubocop-infinum gem :)

2020-09-10 09:11 UTC, d4be4st commented on Gemfile
> +  gem 'web-console', '>= 3.3.0'
we do not need this because better_errors

2020-09-10 09:11 UTC, d4be4st commented on app/views/layouts/application.html.erb
> +<!DOCTYPE html>
slim

2020-09-10 09:11 UTC, d4be4st commented on config/credentials.yml.enc
> +yM5ZdLjr5eqZUd0YAp6+xdbc/rnDcqDjNP1gK8+lGMA+/MiB/o1LpWZYq7rX24BgpYOixBxtUwR9UL9lJhBssTOOY1Sw27hiPPRCi40rE7xUqpJEr0X5HiQCdBWdi6z53LD/jmZ2AxrH+H2HVqZ2peRBqx6tgDv/54qNk2lMtGBTJknqRGeQMIK6a4ZGkSdQNwmYLG8
we do not use credentials

2020-09-10 09:11 UTC, d4be4st commented on config/puma.rb
> +max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
```suggestion
max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 1 }
```

So we can use pry more easily in development

2020-09-10 09:11 UTC, d4be4st commented on config/storage.yml
> +test:
remove, not using active-storage

2020-09-10 09:11 UTC, d4be4st commented on config/application.rb
> +require "active_storage/engine"
comment out, not using

2020-09-10 09:11 UTC, d4be4st commented on config/application.rb
> +require "action_mailbox/engine"
comment out, not using

2020-09-10 09:11 UTC, d4be4st commented on config/application.rb
> +require "action_text/engine"
comment out, not using

2020-09-10 09:11 UTC, d4be4st commented on config/application.rb
> +require "action_cable/engine"
comment out, not using

2020-09-10 09:11 UTC, d4be4st commented on spec/spec_helper.rb
> +# This file was generated by the `rails generate rspec:install` command. Conventionally, all
merge into rails_helper.

2020-09-10 10:51 UTC, uncoverd commented on .git-hooks/pre_push/zeitwerk_check.rb
> +      class ZeitwerkCheck < Base
I may be the odd one here, but I think this should be pushed to the CI steps. A build **shouldn't** pass without getting a green light from this check. Your app might not boot, and you won't even realise it with our current deploy tooling.

I would also **add** Rubocop to CI while keeping it in overcommit. It may seem like double the work, but the overcommit check gives us a tight feedback loop for files in the commit, while the CI check gives us confidence that all the codebase is in a nice state and that people didn't disable/break overcommit un/knowingly.

2020-09-10 12:24 UTC, martincekada commented on .rubocop.yml
> +  - rubocop-rspec
I propose to open PR on rails-template for this also 👍 👎 ?

2020-09-10 12:24 UTC, martincekada commented on Gemfile
> +  gem 'web-console', '>= 3.3.0'
I propose to open PR on rails-template for this also 👍 👎 ?

2020-09-10 12:27 UTC, martincekada commented on config/puma.rb
> +max_threads_count = ENV.fetch("RAILS_MAX_THREADS") { 5 }
I propose to open PR on rails-template for this also 👍 👎 ?

2020-09-10 12:38 UTC, d4be4st commented on .rubocop.yml
> +  - rubocop-rspec
There already is https://github.com/infinum/default_rails_template/pull/54

2020-09-10 12:39 UTC, d4be4st approved these changes

2020-09-10 13:20 UTC, cilim commented on config/deploy.rb
> +# set :background_worker, 'dj' / 'sidekiq'
can we add this too?
`set :sidekiq_web_namespace, :admin`

2020-09-10 13:22 UTC, cilim commented on config/deploy.rb
> +      # invoke :'background_workers:restart'
and also, related to my previous comment, this should be here too if the developer uses sidekiq and has in plan to use the sidekiq dashboard:
```
invoke :link_sidekiq_assets
```

2020-09-11 09:47 UTC, d4be4st commented on .git-hooks/pre_push/zeitwerk_check.rb
> +      class ZeitwerkCheck < Base
I would still leave this one here :)

since we are using bin/build.sh we could add these there later

2020-09-11 10:22 UTC, closed without merging

2020-09-11 10:22 UTC, uncoverd commented on .git-hooks/pre_push/zeitwerk_check.rb
> +      class ZeitwerkCheck < Base
My selfish reasons for removing it is really simple, it takes too long to push anything! If we have it in the pre-push its 7 seconds on push and 7 seconds on CI 😢

```
jaka@MacBook-Pro  ~/Work/rails-underline   master  time bundle exec rake zeitwerk:check
Hold on, I am eager loading the application.

WARNING: The following directories will only be checked if you configure
them to be eager loaded:

  /Users/jaka/Work/rails-underline/spec/mailers/previews

You may verify them manually, or add them to config.eager_load_paths
in config/application.rb and run zeitwerk:check again.

Otherwise, all is good!
bundle exec rake zeitwerk:check  7.58s user 4.85s system 90% cpu 13.735 total
```